function renderScan(){
  const s=state.scan;
  if(s.selected){
    const v=s.selected.variants.find(x=>x.label===s.finish)||s.selected.best;
    const value=(v?.market||0)*(CONDITIONS.find(c=>c.id===s.condition)?.multiplier??1)*s.qty;
    return '<div class="stack"><button class="back" data-act="rescan">‹ Rescan</button><div class="card"><div class="row"><img class="art md" src="'+h(s.selected.imageSmall)+'" alt=""><div><h2 class="h2 serif">'+h(s.selected.name)+'</h2><p class="sub">'+h(s.selected.setName)+' · '+h(s.selected.number)+'/'+h(s.selected.printedTotal)+'</p><div class="price" style="font-size:26px;margin-top:8px">'+money(value)+'</div><p class="sub">'+h(v?.label)+'</p></div></div><div class="quotes" style="margin-top:12px"><div class="quote"><span>LOW</span>'+money(v?.low)+'</div><div class="quote"><span>MID</span>'+money(v?.mid)+'</div><div class="quote"><span>HIGH</span>'+money(v?.high)+'</div></div></div><div class="card stack"><div class="pills">'+((s.selected.variants.length?s.selected.variants:[s.selected.best]).map(x=>'<button class="pill '+(s.finish===x.label?'on':'')+'" data-act="finish" data-v="'+h(x.label)+'">'+h(x.label)+'</button>').join(''))+'</div><div class="pills">'+CONDITIONS.map(c=>'<button class="pill '+(s.condition===c.id?'on':'')+'" data-act="cond" data-v="'+c.id+'">'+c.id+'</button>').join('')+'</div></div><button class="btn gold" data-act="add">Add to binder</button><button class="btn ghost" data-act="add-list">Add and list for trade</button></div>';
  }
  return '<div class="stack"><div><h1 class="h1 serif">Trove</h1><p class="sub">Align a card, or search the catalog</p></div><div class="camera">'+(s.shot?'<img class="shot" src="'+s.shot+'" alt="">':'<video id="cam" playsinline muted autoplay></video>')+'<div class="frame"></div></div><div class="shutter-row"><label class="icon-btn" style="display:grid;place-items:center">🖼<input type="file" accept="image/*" capture="environment" hidden id="file"></label><button class="shutter" data-act="shutter"></button><button class="icon-btn" data-act="lookup">⌕</button></div><input id="q" placeholder="Charizard, Umbreon VMAX…" value="'+h(s.query)+'"><button class="btn gold" '+(s.busy?'disabled':'')+' data-act="lookup">'+(s.busy?'Looking up…':(s.query?'Search catalog':'Demo: look up Charizard'))+'</button><p class="hint">Safari → Share → Add to Home Screen. Camera will not work inside Grok.</p>'+(s.error?'<p class="sub" style="color:var(--ember)">'+h(s.error)+'</p>':'')+'</div>';
}
function renderBinder(){
  const b=state.binder,total=state.store.binder.reduce((s,c)=>s+adjusted(c),0),selected=state.store.binder.find(c=>c.id===b.open);
  if(selected){
    return '<div class="stack"><button class="back" data-act="binder-back">‹ Binder</button><img class="art" style="max-width:220px;margin:0 auto" src="'+h(selected.imageLarge||selected.image)+'" alt=""><div><h2 class="h2 serif">'+h(selected.name)+'</h2><p class="sub">'+h(selected.setName)+'</p></div><div class="card"><div class="row" style="justify-content:space-between"><span class="mist">Adjusted</span><span class="price" style="font-size:26px">'+money(adjusted(selected))+'</span></div></div><div class="card stack"><select id="bcond">'+CONDITIONS.map(c=>'<option value="'+c.id+'" '+(selected.condition===c.id?'selected':'')+'>'+c.title+'</option>').join('')+'</select><label class="sub"><input type="checkbox" id="blist" '+(selected.listed?'checked':'')+'> Listed for trade</label><button class="btn ghost" data-act="remove">Remove from binder</button></div></div>';
  }
  const cards=state.store.binder.filter(c=>{const hit=!b.q||c.name.toLowerCase().includes(b.q.toLowerCase());if(b.filter==='trade')return hit&&c.listed;if(b.filter==='grails')return hit&&adjusted(c)>=50;return hit;});
  return '<div class="stack"><div><h1 class="h1 serif">Binder</h1><div class="price" style="font-size:34px">'+money(total)+'</div><p class="sub">'+state.store.binder.length+' cards</p></div><input id="bq" placeholder="Search your binder" value="'+h(b.q)+'"><div class="pills">'+[['all','All'],['trade','For trade'],['grails','Grails']].map(x=>'<button class="pill '+(b.filter===x[0]?'on':'')+'" data-act="bfilter" data-v="'+x[0]+'">'+x[1]+'</button>').join('')+'</div>'+(cards.length?('<div class="grid">'+cards.map(c=>'<button class="card" data-act="bopen" data-id="'+c.id+'"><img class="art" src="'+h(c.image)+'" alt=""><div style="margin-top:8px;font-weight:700">'+h(c.name)+'</div><div class="price">'+compact(adjusted(c))+'</div></button>').join('')+'</div>'):'<div class="empty"><h3>Binder is empty</h3><p class="mist">Scan a card to start.</p></div>')+'</div>';
}
function renderTrade(){
  const t=state.trade;
  if(t.inbox){
    return '<div class="stack"><button class="back" data-act="inbox-back">‹ Trade floor</button><h1 class="h1 serif">Inbox</h1>'+(state.store.offers.length?state.store.offers.map(o=>'<div class="card stack"><div class="row" style="justify-content:space-between"><span class="sub">You → '+h(o.owner)+'</span><span class="status-chip">'+h(o.status)+'</span></div><strong>'+h(o.listingName)+'</strong><p class="sub">'+h(o.message)+'</p>'+(o.reply?'<div class="quote" style="text-align:left">'+h(o.reply)+'</div>':'')+(o.status==='accepted'?'<button class="btn gold" data-act="complete" data-id="'+o.id+'">Mark shipped</button>':'')+'</div>').join(''):'<div class="empty"><h3>No offers yet</h3></div>')+'</div>';
  }
  if(t.offerFor){
    const listing=t.offerFor;
    const offerValue=t.picked.reduce((s,id)=>s+adjusted(state.store.binder.find(c=>c.id===id)||{market:0,quantity:1,condition:'NM'}),0)+(Number(t.cash)||0);
    return '<div class="stack"><button class="back" data-act="offer-back">‹ Listing</button><h2 class="h2 serif">Propose trade</h2><div class="card row"><img class="art sm" src="'+h(listing.img)+'" alt=""><div><strong>'+h(listing.name)+'</strong><div class="price">'+money(listing.asking)+'</div></div></div>'+state.store.binder.map(c=>'<button class="card row" data-act="toggle-pick" data-id="'+c.id+'"><img class="art sm" src="'+h(c.image)+'" alt=""><div style="flex:1"><strong>'+h(c.name)+'</strong></div><span>'+(t.picked.includes(c.id)?'●':'○')+'</span></button>').join('')+'<input id="cash" placeholder="Cash on top (USD)" value="'+h(t.cash)+'"><div class="row" style="justify-content:space-between"><span class="mist">Offer</span><span class="price">'+money(offerValue)+'</span></div><button class="btn gold" data-act="send-offer">Send offer</button></div>';
  }
  if(t.open){
    const listing=state.store.listings.find(l=>l.id===t.open); if(!listing) return '';
    return '<div class="stack"><button class="back" data-act="trade-back">‹ Trade floor</button><div class="row"><img class="art md" src="'+h(listing.img)+'" alt=""><div><h2 class="h2 serif">'+h(listing.name)+'</h2><div class="price" style="font-size:26px">'+money(listing.asking)+'</div><p class="sub">'+flag(listing.country)+' '+h(listing.owner)+' · '+h(listing.city)+'</p></div></div><div class="card"><p class="sub">LOOKING FOR</p><p>'+h(listing.wants)+'</p><p class="mist">'+h(listing.note)+'</p></div>'+(listing.local?'<p class="mist">Your listing.</p>':'<button class="btn gold" data-act="propose">Propose a trade</button>')+'</div>';
  }
  const listings=state.store.listings.filter(l=>!l.hidden);
  const countries=[...new Set(listings.map(l=>l.country))];
  const filtered=listings.filter(l=>(!t.q||l.name.toLowerCase().includes(t.q.toLowerCase()))&&(t.country==='ALL'||l.country===t.country));
  return '<div class="stack"><div class="row" style="justify-content:space-between"><div><h1 class="h1 serif">Trade floor</h1><p class="sub">'+listings.length+' listings</p></div><button class="icon-btn" data-act="inbox">☰</button></div><input id="tq" placeholder="Search cards or trainers" value="'+h(t.q)+'"><div class="pills"><button class="pill '+(t.country==='ALL'?'on':'')+'" data-act="tcountry" data-v="ALL">World</button>'+countries.map(c=>'<button class="pill '+(t.country===c?'on':'')+'" data-act="tcountry" data-v="'+c+'">'+flag(c)+' '+c+'</button>').join('')+'</div>'+filtered.map(l=>'<button class="card row" data-act="lopen" data-id="'+l.id+'"><img class="art sm" src="'+h(l.img)+'" alt=""><div style="flex:1"><div class="row" style="justify-content:space-between"><strong>'+h(l.name)+'</strong><span class="price">'+compact(l.asking)+'</span></div><p class="sub">'+flag(l.country)+' '+h(l.owner)+' · '+h(l.city)+'</p></div></button>').join('')+'</div>';
}
function renderYou(){
  const p=state.store.profile,total=state.store.binder.reduce((s,c)=>s+adjusted(c),0),listed=state.store.listings.filter(l=>l.local&&!l.hidden).length;
  return '<div class="stack"><div class="row"><div style="width:64px;height:64px;border-radius:32px;background:linear-gradient(#5a3b1a,#1e140c);display:grid;place-items:center;font-weight:800">'+h(p.name.slice(0,1))+'</div><div><h1 class="h1 serif">'+h(p.name)+'</h1><p class="sub">'+flag(p.country)+' '+countryName(p.country)+'</p></div></div><div class="statrow"><div class="stat"><b>'+state.store.binder.length+'</b><span>Cards</span></div><div class="stat"><b>'+compact(total)+'</b><span>Binder</span></div><div class="stat"><b>'+listed+'</b><span>Listed</span></div><div class="stat"><b>'+state.store.offers.length+'</b><span>Offers</span></div></div><div class="card stack"><input id="pname" value="'+h(p.name)+'"><input id="pcity" placeholder="City" value="'+h(p.city)+'"><select id="pcountry">'+COUNTRIES.map(x=>'<option value="'+x[0]+'" '+(p.country===x[0]?'selected':'')+'>'+x[2]+' '+x[1]+'</option>').join('')+'</select></div><div class="card"><p class="mist" style="font-size:13px">Safari → Share → Add to Home Screen. Native Vision OCR still needs Xcode on a Mac. Unofficial — not affiliated with Nintendo or TCGPlayer.</p></div></div>';
}
